join-message:
  lines:
    - "&7&m------------------------------"
    - "         &e&lServer Network"
    - ""
    - "&e&l° &eWebsite: &dwww.server.com"
    - "&e&l° &eStore: &dstore.server.com"
    - "&e&l° &eDiscord: &ddiscord.gg/server"
    - "&e&l° &eTwitter: &dtwitter.com/server"
    - "&e&l° &eRules: &dserver.com/rules"
    - "&7&m------------------------------"

join-sound:
  sound: "BAT_TAKEOFF"

join-speed:
  velocity: 0.2

chat-format:
  muted:
    message: "&cThis chat is already muted."
  normal:
    message: "%prefix%%player%&7: %message%"

hide-player:
  slot: 5
  show:
    name: "&aShow Players"
    material: "INK_SACK"
    data: 10
    message: "&aPlayers are visible for you!"
    lore:
      - "&7Show all players"
  hide:
    name: "&7Hide Players"
    material: "INK_SACK"
    data: 8
    message: "&cPlayers are hidden for you!"
    lore:
      - "&7Hide all players"


server-selector:
  name: "&9» &6&lServer Selector &9«"
  material: "COMPASS"
  data: 0
  slot: 4
  lore:
    - "&7click to use server selector"

butt:
  name: "&9» &5&lEnderButt &9«"
  material: "ENDER_PEARL"
  amount: 1
  sound: "ORB_PICKUP"
  slot: 6
  lore:
    - "&7click to use ender butt"

double-jump:
  velocity: 2.0
  sound: "BAT_TAKEOFF"
  effect: "FLAME"

commands:
  discord:
    - "&eDiscord: &ddiscord.server.com"
  teamspeak:
    - "&eTeamSpeak: &dts.server.com"
  twitter:
    - "&eTwitter: &dtwitter.com/server"
  telegram:
    - "&eTelegram: &dt.me/server"
  store:
    - "&eStore: &5store.server.com"