system:
  license: ""
  queue: "" # Ezqueue, Portal
  rank: "" # Vault, Aquacore, Zoot, Zoom, Hestia

world:
  no-drop-items:
    message: "&cYou don't have permissions to drop items in spawn."
  no-place-blocks:
    message: "&cYou don't have permissions to place blocks in spawn."
  no-break-blocks:
    message: "&cYou don't have permissions to breaks blocks in spawn."
  border:
    max-x: 300
    max-z: 300
    message: "&cYou can't get past the edge of the map!"
  minehq-hideplayers:
    message: "&bPop!"
    sound: "BLAZE_HIT"

addons:
  protection:
    message: "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
    blocked-commands:
      - "about"
      - "bukkit:about"
      - "bukkit:help"
      - "bukkit:?"
      - "bukkit:me"
      - "bukkit:pl"
      - "bukkit:plugins"
      - "bukkit:ver"
      - "bukkit:version"
      - "icanhasbukkit"
      - "info"
      - "?"
      - "pl"
      - "plugins"
      - "ver"
      - "version"
      - "me"
      - "say"